google maps api on visualizations page
codeforboston/legalhousing pull request #71
Opened 2017-04-05 00:57 UTC by jd2rogers2

@AlexMerritt

2017-04-19 00:10 UTC, abrahamgrubin commented on app/assets/javascripts/listings.js
> +  var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
Remove unused variable

2017-04-19 00:12 UTC, abrahamgrubin commented on app/assets/javascripts/listings.js
> +      var listings = data.filter(function(point){
On success use `JSON.parse(data)`

2017-04-19 00:14 UTC, abrahamgrubin commented on app/assets/javascripts/listings.js
> +        geometry: {type: 'Point', coordinates: [parseInt(listing.latitude, 10), parseInt(listing.longitude, 10)]},
Remove `parseInt(listing.latitude, 10), parseInt(listing.longitude, 10)` after parsing JSON on a successful response and just have `[listing.latitude, listing.longitude]`

2017-04-19 00:23 UTC, abrahamgrubin requested changes
Please address the issues below: 
1. Research hiding secret key in yml file

2017-04-19 01:07 UTC, abrahamgrubin commented on app/assets/javascripts/listings.js
> +      var listings = data.filter(function(point){
Tried this out and did not do what we expected. This is all set.

2017-05-03 00:40 UTC, mzagaja requested changes
I left some comments. Some of the purposes of the changes were not clear to me and appeared to simply be removing previous work. Can you explain the purpose of these changes?

2017-05-03 00:40 UTC, mzagaja commented on db/migrate/20170404033714_create_phrases.rb
> -class CreatePhrases < ActiveRecord::Migration[5.0]
Instead of deleting the old migration that creates the phrases, would you consider making a new migration that deletes the phrases table?

2017-05-03 00:40 UTC, mzagaja commented on app/models/listing.rb
> -  def check_phrase(phrase)
Why are you deleting this method?

2017-05-03 00:40 UTC, mzagaja commented on app/views/listings/index.html.erb
> -  <div id="viz"></div>
Why are you deleting this visualization?

2017-05-03 00:40 UTC, mzagaja commented on app/views/listings/visualization.html.erb
> -<body>
Why are you deleting this?

2017-05-03 00:40 UTC, mzagaja commented on config/routes.rb
> -  resources :scrapers
Why are you removing the scrapers resource?

2017-05-03 00:52 UTC, jd2rogers2 commented on app/views/listings/index.html.erb
> -  <div id="viz"></div>
because this is on the listings index page, we have a /visualizations with this

2017-05-03 00:53 UTC, jd2rogers2 commented on app/views/listings/visualization.html.erb
> -<body>
i just moved/reordered it, you can see it in the added code too

2017-05-03 00:53 UTC, jd2rogers2 commented on config/routes.rb
> -  resources :scrapers
consolidated see `resources :listings, :phrases, :scrapers` line

2017-05-03 00:55 UTC, mzagaja commented on config/routes.rb
> -  resources :scrapers
Missed that one. Thanks.

2017-05-03 00:58 UTC, jd2rogers2 commented on app/models/listing.rb
> -  def check_phrase(phrase)
not sure, let's keep it then

2017-05-03 01:01 UTC, jd2rogers2 commented on db/migrate/20170404033714_create_phrases.rb
> -class CreatePhrases < ActiveRecord::Migration[5.0]
let's keep phrases all together actually

2017-05-09 23:54 UTC, mzagaja approved these changes

2017-07-19 00:08 UTC, closed without merging