Add Scrapes table to have a record of each time the scraper is run
codeforboston/legalhousing pull request #80
Opened 2017-05-03 00:43 UTC by kfili

- add function to scrapers controller to add scrape meta data
  to Scrapes table
- created_on timestamp in scrapes table can be used for date of
  last scrape

2017-05-03 00:45 UTC, jmartini commented on db/schema.rb
> +  end
I don't think we need this scrapers table, just the scrapes below

2017-05-03 00:48 UTC, mzagaja requested changes

2017-05-03 00:48 UTC, mzagaja commented on app/controllers/scrapers_controller.rb
> +    listing_info, scraper_info = HousingListingScraper.run_scrapers()
FYI Methods without arguments do not requires parenthesis.

2017-05-03 00:48 UTC, mzagaja commented on lib/housing_listing_scraper/padmapper_scraper.rb
> +        return "Paddmaper"
Would this (along with the search url) make more sense as attributes stored in the database as part of the scrapers table?

2017-05-09 23:44 UTC, jmartini commented
I approve of this

2017-05-09 23:46 UTC, mzagaja approved these changes

2017-05-10 00:20 UTC, merged